### ISSUE TITLE
Automatic feature ?

### ISSUE THREAD

**Issue by Miguel-LlamasLanza** [retorquere/zotero-file-hierarchy#10]
Even though I believe this feature is useful when you want to export the zotero structure somewhere else, I would like to see another feature:
I would like this to occur automatically, meaning that I can have a folder with all the PDFs that I have in my library in Zotero (and of course structured in the corresponding sub-folders). 
Is this somehow supported by this tool, or do you know if there is another similar tool supporting this?

**Comment by retorquere** [comment]
It's not a feature of this plugin, and I don't know of any other plugin that does it.

**Comment by Miguel-LlamasLanza** [comment]
Thank you for the quick answer!
Is this other project of yours, called [zottero-better-bibtex](https://github.com/retorquere/zotero-better-bibtex) only used for references? Cannot it be put together with the zotero-file-hierarchy to get automatic exports? Sorry if the question is naive, I am new to this.

**Comment by retorquere** [comment]
> Is this other project of yours, called [zottero-better-bibtex](https://github.com/retorquere/zotero-better-bibtex) only used for references?

Mostly, yes. It will export attachments, but not for automated exports. 

> Cannot it be put together with the zotero-file-hierarchy to get automatic exports?

It could, of sorts, but there are two hurdles:

* it's not (sensibly) possible to do partial exports, and copying over all attachments for any change would have BBT impacting zotero performance, and it's already pretty demanding as it is, and
* crucially, Zotero does not notify extensions to changes to the attachments themselves, so you'd need to make a change to annotations or the parent item to trigger exports of the attachments. 

> Sorry if the question is naive, I am new to this.

No worries, asking for information is always OK.
