### ISSUE TITLE
Alert when it's done

### ISSUE THREAD

**Issue by KiloNovemberDelta** [retorquere/zotero-file-hierarchy#11]
Hello,

Thank you for this wonderful plugin, it helps me a lot!
I would like to know if there is a way to be alert when the process is done? 
Because once I launch the script, I can see the folders of my collections created, and slowly my pdf appears. However, I have a lot of folders, so I have no clue what is the translation's progress, and no way to know once it's done. 
For now, I just let Zotero working on its side for a long period of time, checking if the pdf in some folders match with Zotero's collection, and I cross my fingers that everything is here. 

Maybe it can be a nice feature to have an alert once it's done, or having a progression bar anyhow?  
Thank you again!

**Comment by retorquere** [comment]
This is just a translator, not a plugin, so it can't do any UI interaction.
