### ISSUE TITLE
An error occurred while trying to export the selected file

### ISSUE THREAD

**Issue by 01baftb** [retorquere/zotero-file-hierarchy#2]
I have a library with 700+ items. I was testing zotero-file-hierarchy to confirm everything is running smoothly. The export only occurs partially, followed by the error dialog box which says, "An error occurred while trying to export the selected file.". At the export location, I do see some files/folders that are partially transferred. 

How can I help debug this issue? I enabled Debug output logging. However, will you be able to see the log if I give you debug ID or is it only available to Zotero team? I prefer not to post the entire log here due to privacy reasons. 

Below is portion of the log towards the end where the error occurred: 
I am using Zotero 5.0.61-beta.24+ef4866f97 on Windows 10 x64. 
```
(1)(+0000002): NS_ERROR_FILE_NOT_FOUND Exception: Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsILocalFile.copyTo] Zotero.Translate.ItemGetter.prototype._attachmentToArray/attachmentArray.saveFile@chrome://zotero/content/xpcom/translation/translate_item.js:1160:8 save@File Hierarchy:73:17 doExport@File Hierarchy:85:9 rest@chrome://zotero/content/xpcom/translation/translate.js:1408:24 Zotero.Translate.Base.prototype._translateTranslatorLoaded</<@chrome://zotero/content/xpcom/translation/translate.js:1398:34

(2)(+0000002): Translate: Translation using File Hierarchy failed: [Exception... "Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsILocalFile.copyTo]" nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)" location: "JS frame :: chrome://zotero/content/xpcom/translation/translate_item.js :: Zotero.Translate.ItemGetter.prototype._attachmentToArray/attachmentArray.saveFile :: line 1160" data: no] Zotero.Translate.ItemGetter.prototype._attachmentToArray/attachmentArray.saveFile@chrome://zotero/content/xpcom/translation/translate_item.js:1160:8 save@File Hierarchy:73:17 doExport@File Hierarchy:85:9 rest@chrome://zotero/content/xpcom/translation/translate.js:1408:24 Zotero.Translate.Base.prototype._translateTranslatorLoaded</<@chrome://zotero/content/xpcom/translation/translate.js:1398:34 tryCatcher@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/util.js:16:16 module.exports/Promise.prototype._settlePromiseFromHandler@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/promise.js:512:13 module.exports/Promise.prototype._settlePromise@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/promise.js:569:13 module.exports/Promise.prototype._settlePromise0@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/promise.js:614:5 module.exports/Promise.prototype._settlePromises@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/promise.js:693:13 Async.prototype._drainQueue@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/async.js:133:13 Async.prototype._drainQueues@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/async.js:143:5 Async/this.drainQueues@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/async.js:17:9 url => C:\Users\MyUsername\Desktop\ExportTesting\My Library downloadAssociatedFiles => true automaticSnapshots => true

(5)(+0000002): Translate: Running handler 0 for error

(5)(+0000002): Translate: Running handler 0 for done

(3)(+0000000): Running unlock callbacks

(3)(+0000002): Alert: An error occurred while trying to export the selected file.

(1)(+0000068): [Exception... "Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsILocalFile.copyTo]" nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)" location: "JS frame :: chrome://zotero/content/xpcom/translation/translate_item.js :: Zotero.Translate.ItemGetter.prototype._attachmentToArray/attachmentArray.saveFile :: line 1160" data: no] Zotero.Translate.ItemGetter.prototype._attachmentToArray/attachmentArray.saveFile@chrome://zotero/content/xpcom/translation/translate_item.js:1160:8 save@File Hierarchy:73:17 doExport@File Hierarchy:85:9 rest@chrome://zotero/content/xpcom/translation/translate.js:1408:24 Zotero.Translate.Base.prototype._translateTranslatorLoaded</<@chrome://zotero/content/xpcom/translation/translate.js:1398:34 tryCatcher@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/util.js:16:16 module.exports/Promise.prototype._settlePromiseFromHandler@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/promise.js:512:13 module.exports/Promise.prototype._settlePromise@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/promise.js:569:13 module.exports/Promise.prototype._settlePromise0@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/promise.js:614:5 module.exports/Promise.prototype._settlePromises@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/promise.js:693:13 Async.prototype._drainQueue@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/async.js:133:13 Async.prototype._drainQueues@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/async.js:143:5 Async/this.drainQueues@resource://gre/modules/commonjs/toolkit/loader.js -> resource://zotero/bluebird/async.js:17:9

(3)(+0003678): Starting full-text content processor
```

**Comment by retorquere** [comment]
There must be a string `saving to` in the log somewhere around the error, that would be useful to know. I can't see the logs submitted to Zotero, but you can drop a copy of your log into https://goo.gl/forms/dFD27RHUuArq6UEK2; let me know when you'e uploaded because I don't get notified.

**Comment by 01baftb** [comment]
@retorquere Thank you. I just submitted the debug log.

**Comment by retorquere** [comment]
You may be running into Windows path length problems; the error occurs when exporting `Microstereolithography (1)/Auxiliary/Optical transmission _ transparent electrodes/Electrical and optical properties of deep ultraviolet transparent conductive Gasub2Osub3ITO films by magnetron sputtering.pdf `

**Comment by retorquere** [comment]
No guarantees from me: https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/. I don't use Windows and I have no idea why it's set to 260 by default and what the downsides are of lifting the limit.

**Comment by 01baftb** [comment]
@retorquere Thank you for pointing out the path length issue. I have confirmed the issue was related to path length. Your translator worked smoothly after I renamed few files that had very long path length. 

You may close this issue. It's resolved. 

By default on my Windows 10, the long path length registry was already enabled, thus the registry editing method did NOT work. The article you posted says that few 32-bit application may not support long path lengths (see below). This is a common [issue in the default File Explorer](https://serverfault.com/a/232992) for Windows also. I believe Zotero is built using Electron JS, thus the issue could be arising from there? Question: Should I report this to Zotero dev team??? 

> There is one caveat. This new setting won’t necessarily work with every application out there, but it will work with most. Specifically, any modern applications should be fine, as should all 64-bit applications. Older 32-bit applications need to be manifested in order to work, which really just means that the developer has indicated in the application’s manifest file that the application supports longer paths.

**Comment by retorquere** [comment]
Zotero will use Electron at some point, but right now they build on a customized Firefox. I don't know what version exactly, but I can't imagine they'd use a 32-bit version.

You can always report it on the Zotero forums and see what the devs say back, they're pretty responsive.
