### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by kirk86** [retorquere/zotero-file-hierarchy#3]
Thanks for the great plugin. I know that in the readme is mentioned that you're that moving an item across multiple collections will duplicate it during export but I was wondering if it would be possible to implement this addition so that files are not duplicated among collections. Imagine if you have a huge number of collections. That would be difficult to manually go and delete all those duplicates.

For instance if I have the following example of collections:
```
mypapers
  |
  |-------> new_collection
```

And I move one item from `mypapers` to the `new_collection` during export I ideally wouldn't want to find the same pdf in both places but only under `new_collection`

Is that hard to be implemented as an additional check-box allowing users to chose if they want to keep the duplicated docs during export or not?

**Comment by retorquere** [comment]
It's technically possible to see whether I've exported the attachment before, but not "in what collection does it appear last" -- that information is not available to exporters, and I'm not even entirely sure it is available in Zotero at all. In any case, yes, it is possible to only export attachment once, but not possible to reliably determine where it will show up.

**Comment by retorquere** [comment]
You could give https://gist.github.com/eeefbd3d60c2778644729b4d67bc44b8 a try.

**Comment by kirk86** [comment]
@retorquere thank you, I'll give it a go!
