### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Kullenej** [retorquere/zotero-file-hierarchy#7]
Thank you for this plugin! Is it possible to add a function for auto-updating the export whenever a new item is added to the library?

**Comment by retorquere** [comment]
This isn't really a plugin, it's a script that gets ran by zotero when you export parts of your library. It can't initiate any action itself, zotero translators are entirely reactive.

**Comment by Kullenej** [comment]
Okay, thank you once again for the translator!
